nistats/glm.py
nistats/model.py
nistats/tests/test_glm.py
nistats/utils.py

TST: fix the tests on python 3

---

examples/plot_design_matrix.py
examples/plot_localizer_analysis.py
nistats/design_matrix.py
nistats/hemodynamic_models.py
nistats/tests/test_dmtx.py
nistats/tests/test_glm.py
nistats/tests/test_hemodynamic_models.py
nistats/tests/test_model.py
nistats/tests/test_paradigm.py
nistats/tests/test_regression.py

Started to use more conventional, less jargon naming for many variables

MRG: Better naming

---

examples/plot_design_matrix.py
examples/plot_localizer_analysis.py
examples/plot_spm_auditory.py
examples/plot_spm_multimodal_faces.py
nistats/design_matrix.py
nistats/tests/test_dmtx.py

DataFrames for design matrices

---

nistats/experimental_paradigm.py
nistats/glm.py
nistats/hemodynamic_models.py
nistats/model.py
nistats/regression.py
nistats/utils.py

MRG: Refactored docstrings of hemodynamic models

---

examples/plot_fiac_analysis.py
examples/plot_localizer_analysis.py
nistats/datasets.py
nistats/tests/test_datasets.py

MRG: Adding an example with FIAC dataset

---

nistats/design_matrix.py
nistats/hemodynamic_models.py
nistats/model.py
nistats/regression.py
nistats/tests/test_glm.py
nistats/tests/test_regression.py
nistats/tests/test_utils.py
nistats/utils.py

MRG: Delete unused functions

---

README.rst
examples/plot_design_matrix.py
examples/plot_fiac_analysis.py
examples/plot_localizer_analysis.py
examples/plot_spm_auditory.py
examples/plot_spm_multimodal_faces.py
examples/write_paradigm_file.py
nistats/datasets.py
nistats/design_matrix.py
nistats/experimental_paradigm.py
nistats/glm.py
nistats/hemodynamic_models.py

result on my we procrastination...

various cosmits

---

.travis.yml

Solving pending issues with nilearn upgrade.

scikit learn .13 is required

---

examples/plot_design_matrix.py
examples/plot_fiac_analysis.py
examples/plot_localizer_analysis.py
examples/plot_spm_auditory.py
examples/plot_spm_multimodal_faces.py
nistats/design_matrix.py
nistats/glm.py
nistats/tests/test_dmtx.py
nistats/tests/test_glm.py
nistats/tests/test_paradigm.py

Addresses issues #40 and #41 + remove a little bit of code in examples.
Overall, we rely more systematically on DataFrames to store information on design.

Design matrix glm api

---

examples/plot_thresholding.py
nistats/tests/test_dmtx.py
nistats/tests/test_glm.py
nistats/tests/test_hemodynamic_models.py
nistats/tests/test_model.py
nistats/tests/test_paradigm.py
nistats/tests/test_regression.py
nistats/tests/test_thresholding.py
nistats/tests/test_utils.py
nistats/thresholding.py

Added elementary utilities for thresholding. Addresses part of #28

[MRG] Statistical mapping

---

examples/plot_spm_multimodal_faces.py

add info about dataset used in example plot_spm_multimodal_faces.py

DOC: info update on dataset used in this ex.

---

README.rst

New info edit

---

nistats/design_matrix.py
nistats/tests/test_dmtx.py

MRG: Design matrix misspecification

---

examples/plot_thresholding.py

Some simplifications of the thresholding example + better doc. Addresses  #53

[MRG] Improved thresholding example

---

nistats/datasets.py
nistats/tests/test_datasets.py

Better test datasets, withut download

---

nistats/first_level_model.py

fixed slice time ref assumption. Now defaults to 0

---

examples/plot_spm_auditory.py

fix plot_spm_auditory typo

---

.travis.yml
continuous_integration/install.sh
continuous_integration/show-python-packages-versions.py
nistats/version.py

This PR is simply to update the dependencies (Nilearn now only supports scikit learn 0.14.1 and we need some updates due to patsy 0.2.0 and pandas to 0.13). Moreover I added a travis server to test python 3.5.

dependencies and travis update

---

examples/plot_fiac_analysis.py
examples/plot_localizer_analysis.py
examples/plot_spm_auditory.py
examples/plot_spm_multimodal_faces.py
nistats/design_matrix.py
nistats/first_level_model.py
nistats/tests/test_dmtx.py
nistats/tests/test_first_level_model.py

This PR handles several light changes to first level models that were being mixed with the second level Pr and other small but useful modifications.
1) Progress messages have been refined and verbose documentation adjusted accordingly.
2) paradigms has been changed to events to comply with BIDS terminology
3) a TR warning is given in case the TR value is suspiciously high, likely given in ms instead of s.
4) Patsy text formulas added in contrasts
5) Memcache of contrasts dropped. It easily introduced bugs when repeated across different models and is unnecessary from the computational point of view.
6) Error check of column names of design matrix passed to design matrix creation.
tests updated accordingly. This PR requires merge of #88 to install new dependencies in travis. (Patsy).
Will …

First level upgrades

---

examples/plot_design_matrix.py
examples/plot_localizer_analysis.py
examples/plot_spm_auditory.py
examples/plot_spm_multimodal_faces.py
examples/write_paradigm_file.py
nistats/datasets.py
nistats/design_matrix.py
nistats/experimental_paradigm.py
nistats/tests/test_dmtx.py
nistats/tests/test_first_level_model.py

[MRG] Bids events

---

examples/plot_spm_multimodal_faces.py

simple cleaning

---

nistats/design_matrix.py
nistats/first_level_model.py
nistats/tests/test_dmtx.py

Changed "blank" to None for drift models

---

.travis.yml
README.rst
continuous_integration/install.sh
examples/plot_hrf.py
nistats/design_matrix.py
nistats/hemodynamic_models.py
nistats/tests/test_hemodynamic_models.py
nistats/version.py
setup.py

Making it possible to use a non-convolved set of event (assuming e.g. that the "stimulus model" contains some type of hrf convolution).

MRG: Introduced None hrf

---

README.rst
continuous_integration/install.sh
nistats/datasets.py
nistats/tests/test_datasets.py
nistats/version.py

to download partial openfmri datasets, raw and derivatives per subject alongside FSL statistical results for QA.

openneuro individual file download

---

examples/plot_bids_features.py
nistats/reporting.py
nistats/tests/test_thresholding.py
nistats/tests/test_utils.py
nistats/thresholding.py
nistats/utils.py

reporting utils include the images comparison plot, a contrast plot and a cluster stats table

Openneuro example and reporting utils

---

doc/conf.py
examples/plot_spm_auditory.py
nistats/first_level_model.py

This is a continuation of PR #120 to use more sphinx-gallery features

[MRG] Improve SPM auditory example (continuation of #120)

---

examples/plot_fiac_analysis.py
examples/plot_spm_auditory.py
examples/plot_spm_multimodal_faces.py
nistats/datasets.py
nistats/design_matrix.py
nistats/first_level_model.py
nistats/second_level_model.py
nistats/tests/test_first_level_model.py
nistats/tests/test_second_level_model.py
nistats/tests/test_utils.py

This mostly uupgrades to curretn nibabel API. In place of #126

Nibabel use

---

.travis.yml
README.rst
continuous_integration/install.sh
nistats/utils.py
nistats/version.py

removed calc_lwork

---

examples/01_tutorials/plot_spm_auditory.py
nistats/datasets.py

Trying to fix circleci failure

Trying to fix circelci failure related to spm_auditory

---

nistats/first_level_model.py
nistats/tests/test_first_level_model.py

line 289: signal_scaling in [0, 1, (0,1)]    
admits False which made the following False condition unreachable. 
(my first PR please inform liberally re: protocol etc)
also added the
import nibabel as nib

__init__ method: changed signal_scaling if statement

---

doc/sphinxext/numpydoc/numpydoc.py

Attempts to FIX Sphinx 1.7 related issues with CircleCI. As we are seeing in this PR #167

FIX: CircleCI failure related to Sphinx 1.7

---

examples/01_tutorials/plot_spm_auditory.py

A sign error leaded to the selection of a bad voxel to display the time-course of the model fit and the data.

corrected wrong voxel selection in spm_plot_auditory

---

nistats/hemodynamic_models.py

Fixes issue #176 
Anyway to get visual confirmation?

Variable value is correctly interpolated into the warning text

---

examples/README.txt

Revert "Removed the unnecessary "General Examples" section"

---

examples/02_first_level_models/plot_localizer_analysis.py
examples/02_first_level_models/plot_localizer_surface_analysis.py
nistats/model.py
nistats/version.py

Still needs some more explanation, but the code is relatively simple.

[WIP] Pedagogical example of surface-based analysis

---

nistats/design_matrix.py
nistats/hemodynamic_models.py
nistats/tests/test_dmtx.py
nistats/tests/test_hemodynamic_models.py

[MRG] exposed oversampling parameter

---

nistats/first_level_model.py

[MRG] doc fixes

---

examples/03_second_level_models/plot_second_level_association_test.py

Address #189 
Should probably be integrated with #203

[WIP] Added another second-level example

---

examples/01_tutorials/plot_single_subject_single_run.py
nistats/reporting.py
nistats/tests/test_reporting.py

added output_image argument to plot_design_matrix

---

doc/whats_new.rst
examples/01_tutorials/plot_single_subject_single_run.py
examples/03_second_level_models/plot_oasis.py
examples/03_second_level_models/plot_second_level_association_test.py
examples/03_second_level_models/plot_thresholding.py
nistats/tests/test_thresholding.py
nistats/thresholding.py

[MRG] changed the API and docstring of map_threshold

---

nistats/second_level_model.py
nistats/tests/test_second_level_model.py

A simpler attempt to solve #195 (alternative to #214, that involves larger refactoring).

[MRG] Ad hoc fix of 4D image problem

---

doc/install_doc_component.html

The link pointing to Anaconda package seems like moved/renamed. This PR fixes that.
Please let me know if that is not an appropriate link

MAINT: Anaconda install requirements

---

doc/index.rst
doc/themes/nistats/layout.html

DOC: Fix links in front end gallery

---

nistats/datasets.py

[MRG] boto3/botocore is imported only for openneuro fetcher

---

nistats/__init__.py

[WIP] Issue DeprecationWarning regarding end of Python2 support

---

nistats/tests/test_first_level_model.py

Addresses #247
Realized that some tests were mistakenly producing singular design matrices, hence were doing fitting noise ;-(

[MRG] Fixed erroneous tests

---

examples/01_tutorials/plot_first_level_model_details.py
nistats/reporting.py

Improvements based on Neurospin training.
Addresses #275

[MRG] Fix tutorials

---

nistats/tests/test_first_level_model.py

Some files were generated by the tests in the library directory.

cleaned generated output of tests

---

nistats/first_level_model.py
nistats/second_level_model.py
nistats/tests/test_first_level_model.py
nistats/tests/test_second_level_model.py

Fix memory caching issue when doing .compute_contrast in SecondLevelModel

---

nistats/first_level_model.py

For issue #284 
Mutable default args are a source of hard to diagnose bugs. This fixes it.

[MRG] Fixed: param img_filters no longer has a mutable arg ([]) as default

---

.circleci/config.yml

- master branch and new branches are always built from scratch.
- Existing branches cache their built documentation & reuse that to only
rebuild any differences.
- The cahce is purged daily, hence the first push of the day is rebuilt from
scratch.

[MRG] CircleCI builds are more efficient

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md

- Indicating question should be posted on Neurostars.

Added Github issue templates for bug report & feature requests

---

.travis.yml
continuous_integration/install.sh

[WIP] Add coverage check to Nistats

---

nistats/design_matrix.py
nistats/first_level_model.py

[MRG] fixed 3 dosctrings

---

examples/01_tutorials/plot_first_level_model_details.py
examples/02_first_level_models/plot_fiac_analysis.py
examples/03_second_level_models/plot_oasis.py
nistats/_utils/helpers.py
nistats/first_level_model.py
nistats/second_level_model.py
nistats/tests/test_first_level_model.py
nistats/tests/test_helpers.py
nistats/tests/test_second_level_model.py

[MRG] Replace param `mask` with `mask_img` in First & Second Level Models for Nilearn parity

---

examples/01_tutorials/plot_first_level_model_details.py
examples/02_first_level_models/plot_localizer_surface_analysis.py
nistats/datasets.py
nistats/tests/test_datasets.py

[MRG] dowloading new localizer dataset + adapted examples

---

doc/whats_new.rst
nistats/__init__.py

FIX: Do not unconditionally display Python 2 deprecation

---

.circleci/config.yml
continuous_integration/install.sh
doc/conf.py

Pinned Conda to version 4.6 due to incompatibilities & errors in 4.7.5

---

nistats/first_level_model.py
nistats/tests/test_dmtx.py

As per https://github.com/nistats/nistats/issues/369#issuecomment-512987725

Fixed incorrect docstring in run_glm()

---

examples/01_tutorials/plot_first_level_model_details.py

minor corrections of typos

---

examples/02_first_level_models/plot_fir_model.py
nistats/design_matrix.py
nistats/first_level_model.py
nistats/hemodynamic_models.py
nistats/tests/test_dmtx.py
nistats/tests/test_hemodynamic_models.py

This PR adds an example with a Finite Impulse Response (FIR) model, which is a non-parametric way of fitting the hemodynamic response in fMRI.
Took this opportunity to clean some technical details, like the oversampling factor that should not be 1.

[WIP] Fir example

---

examples/02_first_level_models/plot_fir_model.py

[MRG] fixed failing example

---

nistats/design_matrix.py
nistats/tests/test_dmtx.py

[MRG] warning + upper bound on number of drift columns

---

.circleci/config.yml
.travis.yml
README.rst
appveyor.yml
continuous_integration/install.sh
continuous_integration/show-python-packages-versions.py
doc/conf.py
nistats/contrasts.py
nistats/first_level_model.py
nistats/reporting/_plot_matrices.py
nistats/second_level_model.py
nistats/tests/test_contrasts.py
nistats/version.py
requirements-build-docs.txt
requirements-dev.txt

needed for merging into nilearn

remove dependency on patsy

---

examples/03_second_level_models/plot_second_level_association_test.py
examples/03_second_level_models/plot_second_level_one_sample_test.py
nistats/datasets.py
nistats/first_level_model.py
nistats/reporting/_get_clusters_table.py
nistats/tests/test_first_level_model.py
nistats/tests/test_second_level_model.py
nistats/tests/test_thresholding.py
nistats/thresholding.py
nistats/utils.py

`get_data` is deprecated in nibabel

Use a get data function

---

doc/whats_new.rst
examples/03_second_level_models/plot_second_level_association_test.py

missing variables in localizerd dataset are no longer None, but n/a

Fix: Missing variables in localizerd dataset are no longer None, but n/a

---

examples/01_tutorials/plot_first_level_model_details.py
examples/01_tutorials/plot_single_subject_single_run.py
examples/02_first_level_models/plot_adhd_dmn.py
examples/02_first_level_models/plot_bids_features.py
examples/02_first_level_models/plot_fiac_analysis.py
examples/02_first_level_models/plot_fir_model.py
examples/02_first_level_models/plot_localizer_surface_analysis.py
examples/02_first_level_models/plot_spm_multimodal_faces.py
examples/03_second_level_models/plot_oasis.py
examples/03_second_level_models/plot_second_level_association_test.py
examples/03_second_level_models/plot_second_level_one_sample_test.py
examples/03_second_level_models/plot_second_level_two_sample_test.py
examples/03_second_level_models/plot_thresholding.py
examples/04_low_level_functions/plot_design_matrix.py
examples/04_low_level_functions/plot_hrf.py
examples/04_low_level_functions/plot_second_level_design_matrix.py
examples/04_low_level_functions/write_events_file.py
examples/05_complete_examples/plot_bids_analysis.py
examples/05_complete_examples/plot_haxby_block_classification.py
examples/05_complete_examples/plot_surface_bids_analysis.py

- fix some typos
- add missing words
- make structure more homogeneous across examples
- address further questions and unclear parts in comments
First of all, I would like to apologize for any unnecessary change I made and for potentially wrong and/or misleading adaptions. I wasn't sure about one or the other thing...
I tried to limit the changes in the PR to wording, typos, missing/wrong words, punctuations, etc. . However, there were some other things I would like to address, but wasn't sure on how/where to do it best and if it's useful at all. A put together a list below and are happy to work on this further, either within this PR or a new one.
- in [2.1.2.1.](https://nistats.github.io/auto_examples/01_tutorials/plot_first_level_model_details.html#retrieving-the-data) should the …

address typos, missing words and structure throughout tutorials

---

azure-pipelines.yml
doc/themes/nistats/layout.html
doc/whats_new.rst
nistats/__init__.py
nistats/tests/test_init.py
nistats/version.py
setup.cfg

- Added New Deprecation warning
- Removed old deprecation warnings and test.
- Bumped version to 0.0.1rc
- installation with Nilearn 0.7.0 raises a warning.
- Updated news section & whats_new.

Preparation for last release
