examples/plot_design_matrix.py, examples/plot_hrf.py, examples/plot_localizer_analysis.py, examples/plot_spm_auditory.py, examples/plot_spm_multimodal_faces.py, nistats/design_matrix.py, nistats/hemodynamic_models.py, nistats/tests/test_dmtx.py, nistats/tests/test_hemodynamic_models.py
This is an update of hrf module. Fixes a numerical issue, improves docstrings, adds  an example.
Addresses #36 and #34. 
The most debattable change is the removal of the name 'canonical' for the 'glover' hrf, because this name is unclear (in spm, the canonical hrf is not that one). This will break the compatibility with nipy.
What do people think about that ?
=> MRG: hrf refactor

doc/index.rst, doc/modules/reference.rst, doc/themes/nistats/layout.html, examples/plot_bids_analysis.py, examples/plot_hrf.py, examples/plot_second_level_button_press.py, examples/plot_second_level_design_matrix.py, examples/plot_spm_multimodal_faces.py, nistats/datasets.py, nistats/design_matrix.py, nistats/first_level_model.py, nistats/second_level_model.py, nistats/tests/test_datasets.py, nistats/tests/test_dmtx.py, nistats/tests/test_first_level_model.py, nistats/tests/test_second_level_model.py, nistats/tests/test_utils.py, nistats/utils.py
This PR introduces the first_level_models_from_bids object that allows to automatically extract relevant files by just providing a bids directory. This goes along what seem to be stable agreements on the bids derivatives document still under discussion. Particular on how to name preprocessed bold files and other simple problems. Moreover a downloader for all openfmri datasets is provided alongside a downloader for a downsampled language localizer dataset in the bids format on top of which an example is built for the documentation. All tests and documentation are complete.
The only thing missing is to host the resampled language localizer dataset in the cea server and to first merge the sphinx PR on which this PR depends. Then it will just be a matter of a quick update for this PR.
=> Bids utilities

examples/plot_bids_analysis.py, examples/plot_second_level_button_press.py, examples/plot_second_level_design_matrix.py, nistats/design_matrix.py, nistats/second_level_model.py, nistats/tests/test_dmtx.py, nistats/tests/test_second_level_model.py
This is a PR preceding permutation methods, the second level model was failing on some of my datasets due to the way the design matrix was being created and the api was more complicated that it needs to be. 
So now the second level design matrix is simply a list of contrasts and confounders. Like in SPM if you are passing directly the maps you would need to create one second level model per contrast to test. Nonetheless using FirstLevelModels as second_level_input allows to specify the first level contrast directly in the second level compute contrast function to avoid creating multiple second level models. So we keep the same flexibility we had before with a simpler API.
The plan in the following PRs is to connect permutation methods and mixed effects directly as an output_type option in …
=> Second level fit corrections

nistats/datasets.py
Fixes #160 
- Added helper function ```_check_import_boto3```.
- This helper function is used at two function relevant to openneuro
to ```import boto3``` and raises an error if not installed with a user friendly info.
=> Moved import boto3 to function level

nistats/reporting.py
Building the docs locally, I find this doesn't change the appearance of the outputs [here](https://nistats.github.io/auto_examples/04_low_level_functions/plot_design_matrix.html). A random survey of other pages also failed to reveal changes in images.
It's unclear to me if this should be replaced with anything, or was perhaps a hack to correct some other source of global state change during development. Please let me know if you think anything more is required.
Closes #164.
=> FIX: Remove global MPL state change

nistats/version.py, setup.py
Fixes #154 
- User friendly information about installing dependencies is not shown with Python 3. This PR improves that.
- Changed the order of the dependencies required at installation. For instance, scikit-learn is down the order which should be above nilearn. Same with nibabel.
- Turned 'required_at_installation' for nibabel as True as it is one of the dependency and should be required before nilearn.
=> MAINT: improves error message when dependencies are not installed

nistats/design_matrix.py, nistats/first_level_model.py, nistats/second_level_model.py, nistats/tests/test_first_level_model.py, nistats/tests/test_second_level_model.py
Since Pandas 0.23.0, the following warning has been raised:
```
[...]/nistats/second_level_model.py:405: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
labels, results = mem_glm(Y, self.design_matrix_.as_matrix(),
```
These have been equivalent at least since version 0.12.0:
* [pandas.DataFrame.as_matrix()](https://pandas.pydata.org/pandas-docs/version/0.12/generated/pandas.DataFrame.as_matrix.html)
* [pandas.DataFrame.values](https://pandas.pydata.org/pandas-docs/version/0.12/generated/pandas.DataFrame.values.html)
=> ENH: Replace DataFrame.as_matrix() with .values

examples/README.txt
Fix for #151 
Now getting a disappearing whitespace in its place.
The large whitespace is there if I scroll to the top of the page and disappears when I start scrolling down.
Ideas?
=> Removed the unnecessary "General Examples" section

examples/03_second_level_models/plot_oasis.py
This example is meant to show that it is relatively easy to run a second-level analysis with nistats, here in the case of VBM data.
Addresses #191
=> WIP Added Oasis example

doc/modules/reference.rst, examples/01_tutorials/plot_first_level_model_details.py, examples/01_tutorials/plot_single_subject_single_run.py, examples/02_first_level_models/plot_localizer_surface_analysis.py, examples/02_first_level_models/plot_spm_multimodal_faces.py, examples/04_low_level_functions/plot_design_matrix.py, examples/04_low_level_functions/write_events_file.py, nistats/datasets.py, nistats/design_matrix.py, nistats/experimental_paradigm.py, nistats/tests/test_datasets.py, nistats/tests/test_dmtx.py, nistats/tests/test_first_level_model.py, nistats/tests/test_paradigm.py, nistats/tests/test_utils.py
=> [MRG] Replace 'paradigm' with 'events', 'experimental paradigm' for BIDS compliance

doc/modules/reference.rst, examples/02_first_level_models/plot_adhd_dmn.py, examples/02_first_level_models/plot_localizer_surface_analysis.py, examples/02_first_level_models/plot_spm_multimodal_faces.py, examples/04_low_level_functions/plot_design_matrix.py, examples/04_low_level_functions/plot_second_level_design_matrix.py, nistats/design_matrix.py, nistats/first_level_model.py, nistats/model.py, nistats/regression.py, nistats/second_level_model.py, nistats/tests/test_dmtx.py, nistats/tests/test_first_level_model.py, nistats/tests/test_reporting.py, nistats/tests/test_utils.py, nistats/utils.py
- nistats.design_matrix.make_design_matrix -> make_first_level_design_matrix
- nistats.design_matrix.create_second_level_design -> make_second_level_design_matrix
- nistats.utils.pos_recipr -> positive_reciprocal.
- nistats.utils.multiple_fast_inv -> nistats.utils.multiple_fast_inverse
issue #184
=> [MRG] Renamed functon names to use more consistent, less redundant vocabulary

nistats/hemodynamic_models.py
`np.ceil` is a conservative interpretation of a float for number of elements to create with `linspace`, ensuring an oversampling rate of at least that specified. If approximate is all that's needed, then `floor` might save a little computation, and `rint` would be the best approximation.
Also proposed in bids-standard/pybids#302.
=> FIX: numpy.linspace parameter num must be integer

nistats/__init__.py, nistats/tests/test_init.py
Same as issue https://github.com/nilearn/nilearn/issues/1877
Also replaced use of six with sys.version_info for Python version determination (stdlib use over ext lib).
=> Added a DeprecationWarning for Python 3.4

nistats/__init__.py, nistats/tests/test_init.py
Lays the groundwork for addressing the issue raised in https://github.com/nilearn/nilearn/pull/1882#discussion_r241610908
Also
- Simplifies testing the 2 deprecation functions.
- Reduced redundant code.
- Sets the stage for solving the glitch where importing Nistats in Py2, 3.4
overrides the warnings filter of subsequent warnings & testing it.
=> [MRG] Address design deficiencies in python deprecation functions & tests

nistats/_utils/testing.py, nistats/tests/test_first_level_model.py, nistats/tests/test_second_level_model.py, nistats/tests/test_utils.py, nistats/utils.py
- Functions moved from /tests/test_first_level_model.py ino /nistats/utils.py:
- write_fake_fmri_data()
- generate_fake_fmri_data()
- Functions moved from /tests/test_utils.py into /nistats/utils.py (some have been renamed):
- write_fake_bold_img()  -->  _write_fake_bold_img()  
- basic_paradigm()  -->  _basic_paradigm()
- basic_confounds()  -->  _basic_confounds()
- create_fake_bids_dataset()
- Duplicate function removed from /tests/test_second_level_model.py:
- write_fake_fmri_data()
=> [MRG] Refactor utility functions useful in testing

nistats/contrasts.py, nistats/second_level_model.py, nistats/tests/test_second_level_model.py
Follow-up to #183, doing the same for SecondLevelModel as I did previously for FirstLevelModel.
=> ENH: Return dictionary of contrast images with "all" argument in second-level model

examples/02_first_level_models/plot_localizer_surface_analysis.py
`fetch_surf_fsaverage5` has been deprecated in nilearn and replaced with `fetch_surf_fsaverage`, which can fetch either fsaverage or fsaverage5, fsaverage5 (the low-resolution mesh) being the default
=> fetch_surf_fsaverage5 -> fetch_surf_fsaverage

nistats/design_matrix.py, nistats/experimental_paradigm.py, nistats/first_level_model.py, nistats/model.py, nistats/regression.py, nistats/tests/test_first_level_model.py, nistats/tests/test_second_level_model.py
some nistats set file local variables for emacs and vim. it is redundant because
it sets them to the defaults of any reasonable configuration, potentially
annoying if these variables have not been marked as safe, and it is not
efficient as it is not done systematically, nor in any nilearn files, nor for
other editors. I therefore suggest we remove these lines before merging into
nilearn.
from nistats dir:
```
find -name '*.py' -exec sed -i '/^# emacs: -\*-.*/d' {} \;
find -name '*.py' -exec sed -i '/^# vi: set.*/d' {} \;
```
=> [MRG] remove file local variables

doc/whats_new.rst, nistats/first_level_model.py
The `run_img` object is not needed after its masked. Deleting it saves (in my case) around 10x the size of the compressed nifti, which frees up a lot of memory for model fitting.
To give more background, I'm trying to run `nistats` on a cloud server with limited memory. It looks like the bottleneck is not model fitting (peaks at ~2 GB with 2 predictors), but rather loading the unmasked nifti. What is a bit confusing to me is that in this instance I have not passed a mask, so `nilearn` is using a dummy mask of all 1s. Yet, the memory foot print of `Y` is about 6-7x smaller than `run_img`. 
Is there any way to load `run_img` in a way that uses less memory to being with?
In any case, the deletion in this PR helps out a bit.
=> Reduce memory by deleting unmasked run_img

doc/whats_new.rst, examples/02_first_level_models/plot_fixed_effects.py, nistats/contrasts.py, nistats/first_level_model.py, nistats/tests/test_contrasts.py, nistats/tests/test_first_level_model.py
=> [MRG] introduced fixed effects model
